name: ai4nth
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - jupyterlab
  - notebook
  - ipykernel
  - joblib
  - openpyxl
  - pyyaml
  - pytorch-cpu
  - pip
  - xgboost
  - lightgbm
  - pip:
      - mapie
